Feature/java parser
VladBytsyuk/genuml pull request #9
Opened 2020-07-02 20:28 UTC by osipaandr

2020-07-02 21:49 UTC, VladBytsyuk requested changes

2020-07-02 21:49 UTC, VladBytsyuk commented on src/main/com/vbytsyuk/genuml/parsers/JavaParser.kt
> +        }
Тут скорее вопрос.
Вообще я рассчитывал, что пустые файлы не приведут к ошибке парсинга, а просто не внесут вклада в ```Model```. ПОтому что они не добавляют никаких элементов в общую диаграмму.
Если выдавать ошибку при нахождении пустого файла, то получается что 1 пустой файл не даст построить диаграмму.

2020-07-02 21:49 UTC, VladBytsyuk commented on src/main/com/vbytsyuk/genuml/parsers/JavaParser.kt
> +            model.elements.add(typeDeclaration.toElement(Coordinate(0, 0)))
Добавь, пожалуйста, именнованые параметры в конструкторе ```Coordinate```. Интуитивно, конечно, понятно что это ```x``` и ```y```, но с именнованными параметрами выглядит очевидней и, как следствие, читается проще.

2020-07-02 21:49 UTC, VladBytsyuk commented on src/main/com/vbytsyuk/genuml/parsers/JavaParser.kt
> +        )
Вот это дублирует метод```Model.addElement()``` из use case. Лучше добавь параметры которых не хватает в ```addModel()```, а то получается одна и та же логика в 2 местах.

2020-07-02 21:49 UTC, VladBytsyuk commented on src/main/com/vbytsyuk/genuml/parsers/JavaParser.kt
> +}
Используй single line expression вместо ```return``` в начале тела метода. А то тут он выглядит как ненужный текст, который только мешает читать.
P.S. вообще оставлять when на одной строке с ```=``` это нормальная практика. не плодит вложенность по отступам и имнтуитивно ясно, что логика ветвится по условиям.
```
fun foo() = when {
    conditionA -> bar()
    conditionB -> baz()
}
```
На мой взгляд это выглядит чище, чем 
```
fun foo() = 
    when {
        conditionA -> bar()
        conditionB -> baz()
    }
```

2020-07-02 21:49 UTC, VladBytsyuk commented on src/main/com/vbytsyuk/genuml/parsers/JavaParser.kt
> +        )
Это тоже неплохо вынести в методы UseCase. 
Идея в том, чтобы можно было изолированно тестировать изменения модели на внутреннем слое. И в идеале сделать так, чтобы других способ поменять модель из внешних слоев не было (например, сделать internal конструкторы классам из domain).

2020-07-02 21:49 UTC, VladBytsyuk commented on src/main/com/vbytsyuk/genuml/parsers/JavaParser.kt
> +                    .nameAsString,
Тут потенциальное место для падения. ```FieldDeclaration.childNodes``` всегда не пустой список? 
Если нет, надо обязательно обработать эту ситуацию.

2020-07-02 21:49 UTC, VladBytsyuk commented on src/main/com/vbytsyuk/genuml/parsers/JavaParser.kt
> +        !this.isAnnotationPresent("NotNull")
Тут нельзя ограничиться только ```!this.isAnnotationPresent("NotNull")```?

2020-07-02 21:49 UTC, VladBytsyuk commented on src/main/com/vbytsyuk/genuml/parsers/JavaParser.kt
> +            AccessSpecifier.PACKAGE_PRIVATE -> VisibilityModifier.INTERNAL
А вот это сложный момент. Вообще ```PACKAGE_PRIVATE != INTERNAL```. Но думаю пока сойдет.

2020-07-02 21:49 UTC, VladBytsyuk commented on src/main/com/vbytsyuk/genuml/parsers/UnexpectedType.kt
> +}
Тут Java код на Kotlin.
Вообще это можно написать так:
```class UnexpectedType(message: String = "Failed to recognize type") : Exception(message) ```

2020-07-02 21:49 UTC, VladBytsyuk commented on src/test/com/vbytsyuk/genuml/parsers/AbstractParserTest.kt
> +}
Это можно внести в тело ```AbstractParserTest```

2020-07-02 21:49 UTC, VladBytsyuk commented on src/test/com/vbytsyuk/genuml/parsers/JavaParserTest.kt
> +        const val CAR_ = "Car"
Неинформативные имена. Не смотря на контент не понятно, для чего эта константа

2020-07-04 09:59 UTC, osipaandr commented on src/main/com/vbytsyuk/genuml/parsers/JavaParser.kt
> +        }
Согласен, я убрал эту проверку

2020-07-04 09:59 UTC, osipaandr commented on src/main/com/vbytsyuk/genuml/parsers/JavaParser.kt
> +            model.elements.add(typeDeclaration.toElement(Coordinate(0, 0)))
Здесь именованные параметры кажутся мне ненужным нагромождением, а читается и так отлично.
Но для (0, 0) я сделал отдельное решение.

2020-07-04 10:00 UTC, osipaandr commented on src/main/com/vbytsyuk/genuml/parsers/JavaParser.kt
> +        )
Добавил недостающие параметры в метод из use case. Этот метод удалил.

2020-07-04 10:00 UTC, osipaandr commented on src/main/com/vbytsyuk/genuml/parsers/JavaParser.kt
> +}
исправил

2020-07-04 10:00 UTC, osipaandr commented on src/main/com/vbytsyuk/genuml/parsers/JavaParser.kt
> +        )
добавил методы `Element.addProperty` и `Element.addMethod` в `Actions.kt`, но их здесь неудобно использовать

2020-07-04 10:00 UTC, osipaandr commented on src/main/com/vbytsyuk/genuml/parsers/JavaParser.kt
> +                    .nameAsString,
Чтоб список был пустым, переменная должна быть без имени, но тогда раньше получаем исключение при парсинге

2020-07-04 10:00 UTC, osipaandr commented on src/main/com/vbytsyuk/genuml/parsers/JavaParser.kt
> +        !this.isAnnotationPresent("NotNull")
ограничился

2020-07-04 10:00 UTC, osipaandr commented on src/main/com/vbytsyuk/genuml/parsers/JavaParser.kt
> +            AccessSpecifier.PACKAGE_PRIVATE -> VisibilityModifier.INTERNAL
Я понимаю, что вещи разные, но предлагаю переделывать позже, если поймём, что надо

2020-07-04 10:00 UTC, osipaandr commented on src/main/com/vbytsyuk/genuml/parsers/UnexpectedType.kt
> +}
переписал

2020-07-04 10:00 UTC, osipaandr commented on src/test/com/vbytsyuk/genuml/parsers/AbstractParserTest.kt
> +}
внёс

2020-07-04 10:01 UTC, osipaandr commented on src/test/com/vbytsyuk/genuml/parsers/JavaParserTest.kt
> +        const val CAR_ = "Car"
Саму константу заинлайнил. Вообще, надо сильно расширять юнит тесты для парсеров, но это в рамках другой задачи сделаем, думаю.

2020-07-04 13:21 UTC, VladBytsyuk commented on src/main/com/vbytsyuk/genuml/usecases/Actions.kt
> +): Element {
Тут чисто стилистическая придирка. По оффициальным стайлгайда Kotlin, когда разбиваешь аргументы метода на новые строки это делается не как в Java (по отступу первого элемента), а каждый аргумент на своей строке с отступом на 1 больший, че объявление метода.
Например:
```
fun foo(
    a: Int,
    b: Int,
    c: Int
) = a + b +c
```

2020-07-04 13:21 UTC, VladBytsyuk commented on src/main/com/vbytsyuk/genuml/usecases/Actions.kt
>  ): Reference {
Зачем двойной отступ?

2020-07-04 13:25 UTC, VladBytsyuk commented on src/main/com/vbytsyuk/genuml/usecases/Actions.kt
>  ): Reference {
Вообще надо будет настройки линтнера идеи вставить в Гит, чтобы у нас были одинаковы ворнинги. И однозначно такие вещи определять. Я этим позже займусь.

2020-07-05 08:28 UTC, merged